// apps/web/src/app/(auth)/login/page.tsx
import { Button } from '@obai/shared/components/ui/button';
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@obai/shared/components/ui/card';
import { Input } from '@obai/shared/components/ui/input';
import { Label } from '@obai/shared/components/ui/label';

export default function LoginPage() {
  return (
    <div className="flex h-screen w-full items-center justify-center bg-gray-50">
      <Card className="w-[350px]">
        <CardHeader>
          <CardTitle>Welcome back</CardTitle>
          <CardDescription>Enter your credentials to connect with Obai.</CardDescription>
        </CardHeader>
        <CardContent>
          <form>
            <div className="grid w-full items-center gap-4">
              <div className="flex flex-col space-y-1.5">
                <Label htmlFor="email">Email</Label>
                <Input id="email" type="email" placeholder="you@example.com" />
              </div>
              <div className="flex flex-col space-y-1.5">
                <Label htmlFor="password">Password</Label>
                <Input id="password" type="password" />
              </div>
            </div>
          </form>
        </CardContent>
        <CardFooter className="flex justify-between">
          <Button variant="outline">Create account</Button>
          <Button>Login</Button>
        </CardFooter>
      </Card>
    </div>
  );
}

// apps/web/app/pages/login.vue
<script setup lang="ts">
import { Button } from '@obai/shared/components/ui/button';
</script>

<template>
  <main class="min-h-screen bg-background text-foreground">
    <div class="mx-auto flex min-h-screen max-w-xl items-center px-6 py-12">
      <section class="w-full space-y-6 rounded-lg border bg-card p-6 text-card-foreground shadow-sm">
        <div class="space-y-2">
          <p class="text-sm font-medium text-muted-foreground">Login</p>
          <h1 class="text-3xl font-semibold tracking-tight">Sign in</h1>
          <p class="text-sm text-muted-foreground">Use the same shared theme in web and mobile.</p>
        </div>
        <form class="space-y-4" @submit.prevent>
          <div class="space-y-2">
            <label class="text-sm font-medium leading-none">Email</label>
            <input type="email" class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2" placeholder="you@example.com" />
          </div>
          <div class="space-y-2">
            <label class="text-sm font-medium leading-none">Password</label>
            <input type="password" class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2" placeholder="••••••••" />
          </div>
          <div class="flex flex-col gap-3 sm:flex-row">
            <Button type="submit">Login</Button>
            <Button variant="outline" as-child>
              <NuxtLink to="/">Back</NuxtLink>
            </Button>
          </div>
        </form>
      </section>
    </div>
  </main>
</template>
